### ISSUE TITLE
Uses spaces and not tabs

### ISSUE THREAD

**Issue by NoahBres** [nizarmah/mipsim#1]
It is common knowledge that tabs is the proven standard. Pls change to tabs.

**Comment by nizarmah** [comment]
Hello Noah,

I'm afraid the repository is still _under construction_.
Once I finalize it, I will be providing documentation and a report.

Have a good day

**Comment by nizarmah** [comment]
Added a README.md to explain the thinking process behind it.

And, if it really does use spaces, I sincerely apologize. I'm a tabs sorta-guy.
